// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCejo7RzydwU_Bc-TVyRf3j-E9QoC-NCRI',
    appId: '1:880784295838:web:ee91184b54bbbbe0af788f',
    messagingSenderId: '880784295838',
    projectId: 'clgjone',
    authDomain: 'clgjone.firebaseapp.com',
    // We no longer use Firebase Storage in the app, but leaving the original
    // bucket value here keeps FirebaseOptions assertions happy.
    storageBucket: 'clgjone.firebasestorage.app',
    measurementId: 'G-22X08D7FYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd8pRA-EVzLqrxzSpVJ8vZ7jiYP6XZEeI',
    appId: '1:880784295838:android:e7b6eb47df5728dfaf788f',
    messagingSenderId: '880784295838',
    projectId: 'clgjone',
    // Keep original bucket value to satisfy FirebaseOptions requirements,
    // even though uploads now go to Cloudinary.
    storageBucket: 'clgjone.firebasestorage.app',
  );
}
